using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Strada.Core.ECS;
using UnityEditor;
using UnityEngine;

using Strada.Core.ECS.Systems;

namespace Strada.Core.Editor.CodeGen
{
    public static class SystemRegistryGenerator
    {
        private const string GeneratedFile = "GeneratedSystemRegistry.cs";

        [MenuItem("Strada/Generate System Registry")]
        public static void GenerateSystemRegistry()
        {
            var systems = FindAllSystems();
            if (systems.Count == 0)
            {
                Debug.Log("[Strada] No ISystem implementations found.");
                return;
            }

            var code = GenerateRegistryCode(systems);

            StradaCodeGenerator.EnsureGeneratedFolder();

            var path = Path.Combine(StradaCodeGenerator.GeneratedFolder, GeneratedFile);
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();

            Debug.Log($"[Strada] Generated system registry with {systems.Count} systems at {path}");
        }

        private static List<SystemInfo> FindAllSystems()
        {
            var result = new List<SystemInfo>();

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.IsDynamic || assembly.FullName.StartsWith("Unity") || assembly.FullName.StartsWith("System"))
                    continue;

                try
                {
                    foreach (var type in assembly.GetTypes())
                    {
                        if (type.IsAbstract || type.IsInterface)
                            continue;

                        if (!typeof(ISystem).IsAssignableFrom(type))
                            continue;

                        var attr = type.GetCustomAttribute<SystemOrderAttribute>();
                        int order = attr?.Order ?? 0;
                        result.Add(new SystemInfo(type, order));
                    }
                }
                catch (ReflectionTypeLoadException ex)
                {
                    foreach (var type in ex.Types)
                    {
                        if (type == null)
                            continue;

                        if (type.IsAbstract || type.IsInterface)
                            continue;

                        if (!typeof(ISystem).IsAssignableFrom(type))
                            continue;

                        var attr = type.GetCustomAttribute<SystemOrderAttribute>();
                        int order = attr?.Order ?? 0;
                        result.Add(new SystemInfo(type, order));
                    }

                    if (StradaCodeGenSettings.VerboseLogging)
                    {
                        string firstExceptionMessage = null;
                        foreach (var loaderEx in ex.LoaderExceptions)
                        {
                            if (loaderEx != null)
                            {
                                firstExceptionMessage = loaderEx.Message;
                                break;
                            }
                        }
                        Debug.LogWarning($"[Strada] Partial type load from assembly '{assembly.GetName().Name}': {firstExceptionMessage}");
                    }
                }
                catch (Exception ex)
                {
                    Debug.LogWarning($"[Strada] Failed to scan assembly '{assembly.GetName().Name}': {ex.Message}");
                }
            }

            result.Sort((a, b) => a.Order.CompareTo(b.Order));
            return result;
        }

        private static string GenerateRegistryCode(List<SystemInfo> systems)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by Strada System Registry Generator");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Strada.Core.ECS;");
            sb.AppendLine("using Strada.Core.DI;");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedSystemRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly Type[] SystemTypes = new Type[]");
            sb.AppendLine("        {");

            foreach (var s in systems)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(s.Type);
                sb.AppendLine($"            typeof({typeName}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(IContainerBuilder builder)");
            sb.AppendLine("        {");

            foreach (var s in systems)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(s.Type);
                sb.AppendLine($"            builder.Register<{typeName}>(Lifetime.Singleton);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static List<ISystem> CreateAll(IContainer container)");
            sb.AppendLine("        {");
            sb.AppendLine("            var systems = new List<ISystem>(SystemTypes.Length);");

            foreach (var s in systems)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(s.Type);
                sb.AppendLine($"            systems.Add(container.Resolve<{typeName}>());");
            }

            sb.AppendLine("            return systems;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static readonly Regex ValidTypeNameRegex = new Regex(@"^[\w.<>,\s]+$", RegexOptions.Compiled);

        private static bool IsValidTypeName(string typeName)
        {
            return !string.IsNullOrEmpty(typeName) && ValidTypeNameRegex.IsMatch(typeName);
        }

        private static string GetFullTypeName(Type type)
        {
            if (!type.IsGenericType)
                return type.FullName?.Replace("+", ".") ?? type.Name;

            var genericDef = type.GetGenericTypeDefinition();
            var baseName = genericDef.FullName;
            if (baseName == null)
                return type.Name;

            var tickIndex = baseName.IndexOf('`');
            if (tickIndex > 0)
                baseName = baseName.Substring(0, tickIndex);

            var args = type.GetGenericArguments();
            var argNamesList = new string[args.Length];
            for (int i = 0; i < args.Length; i++)
            {
                argNamesList[i] = GetFullTypeName(args[i]);
            }
            var argNames = string.Join(", ", argNamesList);

            return $"{baseName.Replace("+", ".")}<{argNames}>";
        }

        private struct SystemInfo
        {
            public Type Type;
            public int Order;

            public SystemInfo(Type type, int order)
            {
                Type = type;
                Order = order;
            }
        }
    }

}
