using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Strada.Core.ECS.World
{
    public sealed class SystemScheduler : IDisposable
    {
        private readonly List<ISystem>[] _systemsByPhase;
        private readonly List<ISystem> _allSystems;
        private bool _initialized;
        private bool _initializing;

        public SystemScheduler()
        {
            int phaseCount = Enum.GetValues(typeof(UpdatePhase)).Length;
            _systemsByPhase = new List<ISystem>[phaseCount];
            for (int i = 0; i < phaseCount; i++)
                _systemsByPhase[i] = new List<ISystem>(8);
            _allSystems = new List<ISystem>(16);
        }

        public void AddSystem(ISystem system, UpdatePhase phase = UpdatePhase.Update)
        {
            if (system == null) throw new ArgumentNullException(nameof(system));

            // C# does not range-check enum casts, so an out-of-range phase would index past
            // _systemsByPhase and abort whatever bootstrap is doing the registration.
            int phaseIndex = (int)phase;
            if ((uint)phaseIndex >= (uint)_systemsByPhase.Length)
                throw new ArgumentOutOfRangeException(nameof(phase),
                    $"UpdatePhase {phaseIndex} is out of range for this scheduler.");

            _systemsByPhase[phaseIndex].Add(system);
            _allSystems.Add(system);

            // Initialize() short-circuits once it has run, so a system registered afterwards
            // would otherwise never receive Initialize at all: a SystemBase subclass then
            // returns immediately from every Update, and a hand-written ISystem runs
            // uninitialized. Both failures are silent.
            if (_initialized)
                InitializeSystem(system);
        }

        public void Initialize()
        {
            if (_initialized || _initializing) return;
            _initializing = true;

            try
            {
                for (int phase = 0; phase < _systemsByPhase.Length; phase++)
                {
                    var systems = _systemsByPhase[phase];
                    for (int i = 0; i < systems.Count; i++)
                        InitializeSystem(systems[i]);
                }
            }
            finally
            {
                _initializing = false;
                _initialized = true;
            }
        }

        /// <summary>
        /// Initializes one system, isolating a throwing OnInitialize the same way RunPhase
        /// isolates a throwing OnUpdate.
        /// </summary>
        /// <remarks>
        /// Without the catch, the first system to throw aborts the loop and every system after
        /// it stays uninitialized — which for SystemBase means Update returns immediately,
        /// forever, with no further sign that anything is wrong.
        /// </remarks>
        private static void InitializeSystem(ISystem system)
        {
            try
            {
                system.Initialize();
            }
            catch (Exception ex)
            {
                UnityEngine.Debug.LogException(ex);
            }
        }

        /// <summary>
        /// Runs the <see cref="UpdatePhase.Initialization"/> phase.
        /// </summary>
        /// <remarks>
        /// The phase had no driver: <c>AddSystem</c> accepted it and <c>Initialize</c> called
        /// <c>Initialize()</c> on its systems, which made the registration look live, but nothing
        /// ever called their <c>Update</c>. Mirrors Unity's PlayerLoop Initialization category,
        /// which runs once per frame ahead of Update.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void InitializationUpdate(float deltaTime) => RunPhase(UpdatePhase.Initialization, deltaTime);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Update(float deltaTime) => RunPhase(UpdatePhase.Update, deltaTime);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void LateUpdate(float deltaTime) => RunPhase(UpdatePhase.LateUpdate, deltaTime);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void FixedUpdate(float fixedDeltaTime) => RunPhase(UpdatePhase.FixedUpdate, fixedDeltaTime);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void RunPhase(UpdatePhase phase, float deltaTime)
        {
            var systems = _systemsByPhase[(int)phase];
            for (int i = 0; i < systems.Count; i++)
            {
#if UNITY_EDITOR
                // Timestamp deltas rather than Stopwatch.StartNew: Stopwatch is a reference type,
                // so the old code heap-allocated one per system per phase per frame — garbage
                // generated by the profiler, inside the interval the profiler is measuring.
                long start = System.Diagnostics.Stopwatch.GetTimestamp();
#endif
                systems[i].Update(deltaTime);
#if UNITY_EDITOR
                long elapsed = System.Diagnostics.Stopwatch.GetTimestamp() - start;
                _lastExecutionTimes[systems[i].GetType()] =
                    elapsed * 1000.0 / System.Diagnostics.Stopwatch.Frequency;
#endif
            }
        }

        public void Dispose()
        {
            // Each Dispose is isolated: one throwing system used to abort the loop, leaving every
            // system below it undisposed — their SubscriptionTokens unreleased and the EventBus
            // slots still holding hard references to them — and propagating the exception out of
            // World.Dispose before the EntityManager's native memory was freed.
            for (int i = _allSystems.Count - 1; i >= 0; i--)
            {
                try
                {
                    _allSystems[i].Dispose();
                }
                catch (Exception ex)
                {
                    UnityEngine.Debug.LogException(ex);
                }
            }

            _allSystems.Clear();
            for (int i = 0; i < _systemsByPhase.Length; i++)
                _systemsByPhase[i].Clear();

#if UNITY_EDITOR
            // Otherwise the profiler windows keep reading timings for systems that no longer exist.
            _lastExecutionTimes.Clear();
#endif
        }

#if UNITY_EDITOR
        private readonly Dictionary<Type, double> _lastExecutionTimes = new Dictionary<Type, double>();
        public IReadOnlyDictionary<Type, double> LastExecutionTimes => _lastExecutionTimes;
#endif
    }
}
