using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Strada.SourceGeneration
{
    /// <summary>
    /// Generates EntityQuery variants for 9-16 components.
    /// Hand-written T1-T8 exist in EntityQuery.cs/EntityQueryExtended.cs.
    /// </summary>
    [Generator]
    public sealed class EntityQueryGenerator : IIncrementalGenerator
    {
        private const int MinComponents = 9;
        private const int MaxComponents = 16;

        /// <summary>
        /// The assembly that owns the Strada.Core.ECS.Query namespace. These types belong in
        /// it and nowhere else.
        /// </summary>
        private const string OwningAssembly = "Strada.Core";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Emitted per-compilation and gated on the assembly name, NOT via
            // RegisterPostInitializationOutput. Post-initialization output has no access to
            // the compilation, so it emitted these types into every assembly that referenced
            // the analyzer: duplicate definitions everywhere, and a hard compile error in any
            // assembly without "Allow unsafe code" (the query structs use raw pointers).
            var isOwningAssembly = context.CompilationProvider
                .Select(static (compilation, _) => compilation.AssemblyName == OwningAssembly);

            context.RegisterSourceOutput(isOwningAssembly, static (ctx, shouldEmit) =>
            {
                if (!shouldEmit) return;

                ctx.AddSource("Strada.Generated.EntityQuery.g.cs",
                    SourceText.From(GenerateAllCode(), Encoding.UTF8));
            });
        }

        private static string GenerateAllCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Strada.Core.ECS.Storage;");
            // The emitted code lives in Strada.Core.ECS.Query, so IComponent resolves by
            // walking up to Strada.Core.ECS — but EntityManager is in the SIBLING namespace
            // Strada.Core.ECS.Core, which namespace walking never reaches. Without this the
            // generated ForEach extensions do not compile.
            sb.AppendLine("using Strada.Core.ECS;");
            sb.AppendLine("using Strada.Core.ECS.Core;");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Core.ECS.Query");
            sb.AppendLine("{");

            for (int n = MinComponents; n <= MaxComponents; n++)
            {
                GenerateDelegate(sb, n);
                GenerateStruct(sb, n);
            }

            GenerateExtensions(sb);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateDelegate(StringBuilder sb, int n)
        {
            sb.Append($"    public delegate void QueryDelegate<");
            AppendTypeParams(sb, n);
            sb.Append(">(int entityIndex");
            for (int i = 1; i <= n; i++) sb.Append($", ref T{i} c{i}");
            sb.Append(") ");
            AppendWhereUnmanaged(sb, n);
            sb.AppendLine(";");
        }

        private static void GenerateStruct(StringBuilder sb, int n)
        {
            sb.Append($"    public readonly struct EntityQuery<");
            AppendTypeParams(sb, n);
            sb.Append("> : IDisposable ");
            AppendWhereComponent(sb, n);
            sb.AppendLine();
            sb.AppendLine("    {");

            for (int i = 1; i <= n; i++)
                sb.AppendLine($"        private readonly ComponentStorage<T{i}> _s{i};");

            sb.Append("        internal EntityQuery(");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ComponentStorage<T{i}> s{i}");
            }
            sb.Append(") { ");
            for (int i = 1; i <= n; i++) sb.Append($"_s{i} = s{i}; ");
            sb.AppendLine("}");

            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.Append($"        public void ForEach(QueryDelegate<");
            AppendTypeParams(sb, n);
            sb.AppendLine("> action) {");

            for (int i = 1; i <= n; i++)
                sb.AppendLine($"            ref var set{i} = ref _s{i}.GetSparseSet();");

            sb.Append("            int ");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"c{i} = set{i}.Count");
            }
            sb.AppendLine(";");

            sb.AppendLine("            unsafe {");
            sb.AppendLine("                int min = c1, idx = 0;");
            for (int i = 2; i <= n; i++)
                sb.AppendLine($"                if (c{i} < min) {{ min = c{i}; idx = {i - 1}; }}");

            sb.Append("                int* ents = idx switch { ");
            for (int i = 0; i < n - 1; i++) sb.Append($"{i} => set{i + 1}.GetDenseEntityPtr(), ");
            sb.AppendLine($"_ => set{n}.GetDenseEntityPtr() }};");

            sb.AppendLine("                for (int i = 0; i < min; i++) {");
            sb.AppendLine("                    int e = ents[i];");

            sb.Append("                    int ");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"d{i} = set{i}.GetDenseIndex(e)");
            }
            sb.AppendLine(";");

            sb.Append("                    if (");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(" || ");
                sb.Append($"d{i} < 0");
            }
            sb.AppendLine(") continue;");

            // Editor / debug build: also reject d{i} >= set{i}.Count before the pointer
            // dereference. SparseSet's invariant guarantees this in release builds; the
            // check catches storage-corruption bugs during development without paying
            // for the comparison in shipping code.
            sb.AppendLine("#if STRADA_ECS_BOUNDS_CHECK || UNITY_EDITOR");
            sb.Append("                    if (");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(" || ");
                sb.Append($"d{i} >= set{i}.Count");
            }
            sb.AppendLine(") throw new System.IndexOutOfRangeException(\"EntityQuery dense index out of bounds\");");
            sb.AppendLine("#endif");

            sb.Append("                    action(e");
            for (int i = 1; i <= n; i++) sb.Append($", ref *(set{i}.GetDataPtr() + d{i})");
            sb.AppendLine(");");

            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        public void Dispose() { }");
            sb.AppendLine("    }");
        }

        private static void GenerateExtensions(StringBuilder sb)
        {
            sb.AppendLine("    public static class GeneratedQueryExtensions {");

            for (int n = MinComponents; n <= MaxComponents; n++)
            {
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.Append($"        public static EntityQuery<");
                AppendTypeParams(sb, n);
                sb.Append($"> Select<");
                AppendTypeParams(sb, n);
                sb.Append(">(this QueryBuilder b) ");
                AppendWhereComponent(sb, n);
                sb.AppendLine();
                sb.Append($"            => new EntityQuery<");
                AppendTypeParams(sb, n);
                sb.Append(">(");
                for (int i = 1; i <= n; i++)
                {
                    if (i > 1) sb.Append(", ");
                    sb.Append($"b.Manager.Store.GetOrCreateStorage<T{i}>()");
                }
                sb.AppendLine(");");
            }

            for (int n = MinComponents; n <= MaxComponents; n++)
            {
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.Append($"        public static void ForEach<");
                AppendTypeParams(sb, n);
                sb.Append($">(this EntityManager em, QueryDelegate<");
                AppendTypeParams(sb, n);
                sb.Append("> action) ");
                AppendWhereComponent(sb, n);
                sb.AppendLine();
                sb.Append($"            => em.Query().Select<");
                AppendTypeParams(sb, n);
                sb.AppendLine(">().ForEach(action);");
            }

            sb.AppendLine("    }");
        }

        private static void AppendTypeParams(StringBuilder sb, int n)
        {
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"T{i}");
            }
        }

        private static void AppendWhereUnmanaged(StringBuilder sb, int n)
        {
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(" ");
                sb.Append($"where T{i} : unmanaged");
            }
        }

        private static void AppendWhereComponent(StringBuilder sb, int n)
        {
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(" ");
                sb.Append($"where T{i} : unmanaged, IComponent");
            }
        }
    }
}
